<div class="mb-10">
    <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
        <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
        Prohibited Content
    </h3>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Illegal Products, Services and Activities.</span> Ads for illegal products, services and activities are prohibited. Ads must comply with all applicable laws, including laws covering what content is allowed in ads and how ads are targeted.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Discrimination.</span>CezAgora Marketplace does not tolerate discrimination based on personal attributes such as age, gender, gender identity, disability, religion, ethnicity, race, color, national origin or sexual orientation. Ads must comply with this as well as all laws, including laws that prohibit discrimination in connection with education, housing, credit, and employment.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Offensive to Good Taste.</span>Ads must not be offensive to good taste. This means ads must not be, for example, hateful, vulgar, sexually suggestive, or violent. In special circumstances, CezAgora Marketplace may determine that an ad that was acceptable is no longer appropriate as we update our policies to reflect new laws or clarify our position.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Fraud and Deception.</span>Ads must not be fraudulent or deceptive. Your product or service must accurately match the content of your ad. Any claims in your ad must have factual support. Do not make deceptive or inaccurate claims about competitive products or services. Do not imply you or your product are affiliated with or endorsed by others without their permission. Do not advertise prices or offers that are inaccurate - any advertised discount, offer or price must be easily discoverable from the link in your ad.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Trademark Infringement.</span>Ads must not use trademarks belonging to third parties unless express permission has been granted by the trademark owner. You should not use trademarks, logos, service marks or company names in a way that would be confusing to the user or imply an affiliation or endorsement when there is none. Trademark owners can send concerns about the use of their trademarks to us via email.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Copyright Infringement.</span>Ads must not use copyrights belonging to third parties unless express permission has been granted by the copyright owner. If you believe in good faith that your copyright has been infringed, please submit a notice of copyright infringement.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Fake Documents and Related Services.</span>Ads for fake documents and related services are prohibited.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Tobacco Products.</span>Ads for tobacco products are prohibited. This includes ads selling or promoting, directly or indirectly, any tobacco products (such as cigarettes, pipes, cigars), alternative tobacco products (such as e-cigarettes or vaporizers), or any related equipment that facilitates the use of tobacco. Lawful products and services which promote quitting tobacco are permitted.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Illicit or Recreational Drugs.</span>Ads that promote the sale or use of illicit or recreational drugs are prohibited.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Weapons, Fireworks and Other Violent Products or Services.</span>Ads related to the promotion, use or sale of weapons, ammunition, fireworks or any other violent product or service are prohibited.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Adult Content.</span>Ads containing adult content, including ads for adult products and services, are prohibited.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Counterfeit</span>Ads for counterfeit goods are prohibited.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Gambling and Sweepstakes.</span>Ads related to gambling or sweepstakes of any kind are prohibited.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Occult Pursuits.</span>Ads for fortune telling, dream interpretations and individual horoscopes are prohibited, except when the emphasis is on amusement rather than serious interpretation.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Health Matters.</span>Ads promoting unrealistic or misleading claims about health improvements, including related to diet and weight loss, are prohibited. Ads promoting unhealthy or unsafe behaviors, such as excessive consumption of an item, are also prohibited. CezAgora Marketplace reserves the right to restrict advertising related to any health matter.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Affiliate Advertising.</span> Ads related to affiliate advertising are prohibited. Publishers may not run in-stream video ads with their sponsored content without CezAgora Marketplace's prior authorization.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Political.</span>Political ads are prohibited, including ads advocating for or against a particular candidate, party, or ballot proposition or otherwise intended to influence an election outcome; ads fundraising for or by political candidates, parties, political action committees or similar organizations, or ballot propositions; and ads exploiting a sensitive political issue even if the advertiser has no explicit political agenda.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Sensitive Events.</span>CezAgora Marketplace does not allow ads that are inappropriate during the time of or in relation to a tragedy, disaster, or similarly sensitive event.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Hacking, Cracking and Circumvention.</span>Ads that promote products or services for hacking, cracking or circumvention are prohibited.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Incomplete Ad.</span>Incomplete ads will be rejected. If your ad is rejected as incomplete, please finalize it and resubmit.</p>
</div>
