<div class="mb-10">
    <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
        <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
        Safety and Privacy
    </h3>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Harm to CezAgora Marketplace or its Members.</span>Ads must not promote or endorse products, services or actions that would result in a breach of CezAgora Marketplace's User Agreement or Privacy Policy, or that may result in harm to CezAgora Marketplace or its members.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Fair and Legal Billing Practices.</span>The products and services advertised in your ad must have fair billing practices and follow all applicable laws.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Malicious Software/Browser.</span>Do not use an ad to promote, install or distribute viruses, worms, spyware, malware, or other malicious software. Software should only be installed with the permission of the user and should be readily removable by the user. Software features should be made apparent to the user, with no undisclosed features or functions that could harm the user or the user’s data, software, or devices. Do not use any browser flaws/exploits to install software or bypass standard browser security restrictions.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Phishing</span>Do not use an ad to promote a website that tricks a user into providing personal or other information.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">HTTPS and HTTP Support.</span>If you collect sensitive information on the site linked to the ad, you must use HTTPS. Sensitive information includes, but is not limited to, financial info, government-issued identification info, medical info, login info such as usernames and passwords and sensitive characteristics such as racial or ethnic origin, political opinions, religious or philosophical beliefs, trade union membership, sexual orientation, criminal record, information regarding minors or students.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Link Behavior.</span>Do not deceive, confuse, or otherwise degrade the experience of members who click on your ad. The domain of your Display URL must match the domain of your Destination URL. All members must be sent to the same destination URL and landing page from a click on your ad. Do not send members to a landing page that generates a pop-up. The landing page must allow users to navigate away from the page, including via the browser’s ‘Back’ button, and return to the page that the ad was displayed on.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Privacy</span>Advertisers are responsible for complying with applicable privacy and data protection laws and regulations. Do not use tracking cookies to track users across sites without full disclosure and consent of the users (e.g. do not use an “ever cookie” or “zombie cookie”).</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Targeting on Sensitive Characteristics.</span>Ads must not target based on sensitive categories such as health, political affiliation/beliefs, racial or ethnic origin, religious or philosophical affiliation/beliefs, alleged/actual commission of a crime, sexual behavior/orientation, trade union membership or income.</p>
</div>
