<div class="mb-10">
    <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
        <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
        Restricted Content
    </h3>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Alcohol</span>Ads for alcoholic products are restricted and only available in certain countries. Such ads must not target members under 25 years of age. If you are interested in placing an ad related to an alcoholic product, please contact us via email.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Animal Products.</span>CezAgora Marketplace reserves the right to limit ads for animals or animal products. Ads for products related to endangered species are prohibited. </p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Dating Services.</span>Ads for dating services are restricted. Such ads may never be targeted at members under 18. The dating services must be legal in the applicable jurisdiction and must not engage in “escort type” services where any person is compensated to participate in the date. CezAgora Marketplace reserves discretion to determine the appropriateness of the service.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Fraud and Deception.</span>Ads must not be fraudulent or deceptive. Your product or service must accurately match the content of your ad. Any claims in your ad must have factual support. Do not make deceptive or inaccurate claims about competitive products or services. Do not imply you or your product are affiliated with or endorsed by others without their permission. Do not advertise prices or offers that are inaccurate - any advertised discount, offer or price must be easily discoverable from the link in your ad.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Soliciting Funds.</span>Ads for soliciting funds are restricted. CezAgora Marketplace allows ads that solicit funds only if they comply with applicable laws and would qualify as tax deductible or charitable in the applicable jurisdiction</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Prescription Drugs.</span>Ads promoting prescription drugs are restricted and require prior authorization. </p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Fake Documents and Related Services.</span>Ads for fake documents and related services are prohibited.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Over-the-Counter Drugs.</span>Ads promoting over-the-counter drugs are restricted and require prior authorization. Ads may only promote over-the-counter drugs in jurisdictions where it is legal and must adhere to all applicable laws and regulations. Such ads must not target members under 18 years of age.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Medical Devices and Medical Treatments.</span>Ads for medical devices and medical treatments are restricted. Ads may only promote medical devices and medical treatments where it is legal and must adhere to all applicable laws and regulations. Such ads must not target members under 18 years of age</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Short-term Loans and Financial Services.</span>Ads for payday loans, paycheck advances or similar short-term loan products are restricted.</p>
    <p class="text-gray-500 mb-3 dark:text-gray-400"><span class="font-bold">Cryptocurrency.</span>Ads related to the buying, selling, or trading of cryptocurrencies are restricted.</p>
</div>
