<?php

return [
    [
        "id"           => 1,
        "name"         => "Standard",
        "uid"          => "standard",
        "courier_id"   => 1,
        "courier_name" => "DPD",
        "courier_uid"  => "dpd",
    ],
    [
        "id"           => 2,
        "name"         => "Cargo",
        "uid"          => "cargo",
        "courier_id"   => 1,
        "courier_name" => "DPD",
        "courier_uid"  => "dpd",
    ],
    [
        "id"           => 4,
        "name"         => "Standard",
        "uid"          => "standard",
        "courier_id"   => 3,
        "courier_name" => "Cargus",
        "courier_uid"  => "cargus",
    ],
    [
        "id"           => 7,
        "name"         => "Next Day",
        "uid"          => "nextday",
        "courier_id"   => 2,
        "courier_name" => "Sameday",
        "courier_uid"  => "sameday",
    ],
    [
        "id"           => 8,
        "name"         => "Standard",
        "uid"          => "standard",
        "courier_id"   => 5,
        "courier_name" => "Fan Courier",
        "courier_uid"  => "fancourier",
    ],
    [
        "id"           => 11,
        "name"         => "Pick & Ship",
        "uid"          => "pickandship",
        "courier_id"   => 7,
        "courier_name" => "GLS",
        "courier_uid"  => "gls",
    ],
    [
        "id"           => 13,
        "name"         => "Prioripost",
        "uid"          => "prioripost",
        "courier_id"   => 10,
        "courier_name" => "Posta Romana",
        "courier_uid"  => "postaromana",
    ],
    [
        "id"           => 15,
        "name"         => "International Rutier",
        "uid"          => "internationalrutier",
        "courier_id"   => 5,
        "courier_name" => "Fan Courier",
        "courier_uid"  => "fancourier",
    ],
    [
        "id"           => 16,
        "name"         => "International Rutier",
        "uid"          => "internationalrutier",
        "courier_id"   => 1,
        "courier_name" => "DPD",
        "courier_uid"  => "dpd",
    ],
    [
        "id"           => 21,
        "name"         => "adresa - easybox",
        "uid"          => "door2locker",
        "courier_id"   => 2,
        "courier_name" => "Sameday",
        "courier_uid"  => "sameday",
    ],
    [
        "id"           => 22,
        "name"         => "adresa - fanbox",
        "uid"          => "door2locker",
        "courier_id"   => 5,
        "courier_name" => "Fan Courier",
        "courier_uid"  => "fancourier",
    ],
    [
        "id"           => 23,
        "name"         => "Regional Express",
        "uid"          => "regionalexpress",
        "courier_id"   => 1,
        "courier_name" => "DPD",
        "courier_uid"  => "dpd",
    ],
    [
        "id"           => 25,
        "name"         => "easybox - adresa",
        "uid"          => "locker2door",
        "courier_id"   => 2,
        "courier_name" => "Sameday",
        "courier_uid"  => "sameday",
    ],
    [
        "id"           => 26,
        "name"         => "easybox - easybox",
        "uid"          => "locker2locker",
        "courier_id"   => 2,
        "courier_name" => "Sameday",
        "courier_uid"  => "sameday",
    ],
    [
        "id"           => 27,
        "name"         => "fanbox - adresa",
        "uid"          => "locker2door",
        "courier_id"   => 5,
        "courier_name" => "Fan Courier",
        "courier_uid"  => "fancourier",
    ],
    [
        "id"           => 28,
        "name"         => "fanbox - fanbox",
        "uid"          => "locker2locker",
        "courier_id"   => 5,
        "courier_name" => "Fan Courier",
        "courier_uid"  => "fancourier",
    ],
    [
        "id"           => 29,
        "name"         => "Standard",
        "uid"          => "standard",
        "courier_id"   => 7,
        "courier_name" => "GLS",
        "courier_uid"  => "gls",
    ],
];
