<?php

return [
    [
        "id"        => 6,
        "name"      => "Anglia (Regatul Unit)",
        "code"      => "GB",
        "favorite"  => 1,
        "sort"      => 2,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 1,
        "name"      => "Afganistan",
        "code"      => "AF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 2,
        "name"      => "Africa de Sud",
        "code"      => "ZA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 3,
        "name"      => "Albania",
        "code"      => "AL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 4,
        "name"      => "Algeria",
        "code"      => "DZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 5,
        "name"      => "Andora",
        "code"      => "AD",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 7,
        "name"      => "Angola",
        "code"      => "AO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 8,
        "name"      => "Anguilla",
        "code"      => "AI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 9,
        "name"      => "Antarctica",
        "code"      => "AQ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 10,
        "name"      => "Antigua si Barbuda",
        "code"      => "AG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 11,
        "name"      => "Antilele Olandeze",
        "code"      => "AN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 12,
        "name"      => "Arabia Saudita",
        "code"      => "SA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 13,
        "name"      => "Argentina",
        "code"      => "AR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 14,
        "name"      => "Armenia",
        "code"      => "AM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 15,
        "name"      => "Aruba",
        "code"      => "AW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 16,
        "name"      => "Australia",
        "code"      => "AU",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 17,
        "name"      => "Austria",
        "code"      => "AT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 18,
        "name"      => "Azerbaidjan",
        "code"      => "AZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 19,
        "name"      => "Bahamas",
        "code"      => "BS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 20,
        "name"      => "Bahrain",
        "code"      => "BH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 21,
        "name"      => "Bangladeș",
        "code"      => "BD",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 22,
        "name"      => "Barbados",
        "code"      => "BB",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 23,
        "name"      => "Belarusia",
        "code"      => "BY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 24,
        "name"      => "Belgia",
        "code"      => "BE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 25,
        "name"      => "Belize",
        "code"      => "BZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 26,
        "name"      => "Benin",
        "code"      => "BJ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 27,
        "name"      => "Bermude",
        "code"      => "BM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 28,
        "name"      => "Bhutan",
        "code"      => "BT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 29,
        "name"      => "Bolivia",
        "code"      => "BO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 30,
        "name"      => "Bonaire, Sfantul Eustatius si Saba",
        "code"      => "BQ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 31,
        "name"      => "Bosnia si Hertegovina",
        "code"      => "BA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 32,
        "name"      => "Botswana",
        "code"      => "BW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 33,
        "name"      => "Brazilia",
        "code"      => "BR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 34,
        "name"      => "Brunei",
        "code"      => "BN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 35,
        "name"      => "Bulgaria",
        "code"      => "BG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 5320,
        "locations" => 0,
    ],
    [
        "id"        => 36,
        "name"      => "Burkina Faso",
        "code"      => "BF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 37,
        "name"      => "Burundi",
        "code"      => "BI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 38,
        "name"      => "Cambodgia",
        "code"      => "KH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 39,
        "name"      => "Camerun",
        "code"      => "CM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 40,
        "name"      => "Canada",
        "code"      => "CA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 41,
        "name"      => "Capul Verde",
        "code"      => "CV",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 42,
        "name"      => "Chad",
        "code"      => "TD",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 43,
        "name"      => "Chile",
        "code"      => "CL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 44,
        "name"      => "China",
        "code"      => "CN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 45,
        "name"      => "Cipru",
        "code"      => "CY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 46,
        "name"      => "Coasta de Fildes",
        "code"      => "CI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 47,
        "name"      => "Columbia",
        "code"      => "CO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 48,
        "name"      => "Comoros",
        "code"      => "KM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 49,
        "name"      => "Congo",
        "code"      => "CG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 50,
        "name"      => "Coreea de Nord",
        "code"      => "KP",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 51,
        "name"      => "Costa Rica",
        "code"      => "CR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 52,
        "name"      => "Croația",
        "code"      => "HR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 53,
        "name"      => "Curaçao",
        "code"      => "CW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 54,
        "name"      => "Danemarca",
        "code"      => "DK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 55,
        "name"      => "Djibouti",
        "code"      => "DJ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 56,
        "name"      => "Dominica",
        "code"      => "DM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 57,
        "name"      => "Ecuador",
        "code"      => "EC",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 58,
        "name"      => "Egipt",
        "code"      => "EG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 59,
        "name"      => "El Salvador",
        "code"      => "SV",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 60,
        "name"      => "Elvetia",
        "code"      => "CH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 61,
        "name"      => "Emiratele Arabe Unite",
        "code"      => "AE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 62,
        "name"      => "Eritrea",
        "code"      => "ER",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 63,
        "name"      => "Estonia",
        "code"      => "EE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 64,
        "name"      => "Etiopia",
        "code"      => "ET",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 65,
        "name"      => "Federatia Rusa",
        "code"      => "RU",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 66,
        "name"      => "Fiji",
        "code"      => "FJ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 67,
        "name"      => "Fillipine",
        "code"      => "PH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 68,
        "name"      => "Finlanda",
        "code"      => "FI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 69,
        "name"      => "Franta",
        "code"      => "FR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 70,
        "name"      => "Gabon",
        "code"      => "GA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 71,
        "name"      => "Gambia",
        "code"      => "GM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 72,
        "name"      => "Georgia",
        "code"      => "GE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 73,
        "name"      => "Georgia de Sud si Insulele Sandwich",
        "code"      => "GS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 74,
        "name"      => "Germania",
        "code"      => "DE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 75,
        "name"      => "Ghana",
        "code"      => "GH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 76,
        "name"      => "Gibraltar",
        "code"      => "GI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 77,
        "name"      => "Grecia",
        "code"      => "GR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 78,
        "name"      => "Grenada",
        "code"      => "GD",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 79,
        "name"      => "Groenlanda",
        "code"      => "GL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 80,
        "name"      => "Guadeloupe",
        "code"      => "GP",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 81,
        "name"      => "Guam",
        "code"      => "GU",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 82,
        "name"      => "Guatemala",
        "code"      => "GT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 83,
        "name"      => "Guernsey",
        "code"      => "GG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 84,
        "name"      => "Guiana Franceza",
        "code"      => "GF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 85,
        "name"      => "Guinea-Bissau",
        "code"      => "GW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 86,
        "name"      => "Guineea",
        "code"      => "GN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 87,
        "name"      => "Guineea Ecuatoriala",
        "code"      => "GQ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 88,
        "name"      => "Guyana",
        "code"      => "GY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 89,
        "name"      => "Haiti",
        "code"      => "HT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 90,
        "name"      => "Honduras",
        "code"      => "HN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 91,
        "name"      => "Hong Kong",
        "code"      => "HK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 92,
        "name"      => "India",
        "code"      => "IN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 93,
        "name"      => "Indonesia",
        "code"      => "ID",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 94,
        "name"      => "Insula Bouvet",
        "code"      => "BV",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 95,
        "name"      => "Insula Heard si Insulele McDonald",
        "code"      => "HM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 96,
        "name"      => "Insulele Aland",
        "code"      => "AX",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 97,
        "name"      => "Insulele Caiman",
        "code"      => "KY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 99,
        "name"      => "Insulele Christmas",
        "code"      => "CX",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 100,
        "name"      => "Insulele Cocos (Keeling)",
        "code"      => "CC",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 101,
        "name"      => "Insulele Cook",
        "code"      => "CK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 102,
        "name"      => "Insulele Falkland (Malvinas)",
        "code"      => "FK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 103,
        "name"      => "Insulele Faroe",
        "code"      => "FO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 104,
        "name"      => "Insulele Man",
        "code"      => "IM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 105,
        "name"      => "Insulele Marianei de Nord",
        "code"      => "MP",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 106,
        "name"      => "Insulele Marshall",
        "code"      => "MH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 107,
        "name"      => "Insulele Norfolk",
        "code"      => "NF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 108,
        "name"      => "Insulele Solomon",
        "code"      => "SB",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 109,
        "name"      => "Insulele Turks si Caicos",
        "code"      => "TC",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 110,
        "name"      => "Insulele Virgine, Marea Britanie",
        "code"      => "VG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 111,
        "name"      => "Insulele Virgine, S.U.A.",
        "code"      => "VI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 112,
        "name"      => "Iordania",
        "code"      => "JO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 113,
        "name"      => "Irak",
        "code"      => "IQ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 114,
        "name"      => "Irlanda",
        "code"      => "IE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 115,
        "name"      => "Islanda",
        "code"      => "IS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 116,
        "name"      => "Israel",
        "code"      => "IL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 117,
        "name"      => "Italia",
        "code"      => "IT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 118,
        "name"      => "Jamaica",
        "code"      => "JM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 119,
        "name"      => "Japonia",
        "code"      => "JP",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 120,
        "name"      => "Jersey",
        "code"      => "JE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 121,
        "name"      => "Kârgâzstan",
        "code"      => "KG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 122,
        "name"      => "Kazahstan",
        "code"      => "KZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 123,
        "name"      => "Kenia",
        "code"      => "KE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 124,
        "name"      => "Kiribati",
        "code"      => "KI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 125,
        "name"      => "Kuweit",
        "code"      => "KW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 126,
        "name"      => "Lebanon",
        "code"      => "LB",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 127,
        "name"      => "Letonia",
        "code"      => "LV",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 128,
        "name"      => "Liberia",
        "code"      => "LR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 129,
        "name"      => "Libia",
        "code"      => "LY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 130,
        "name"      => "Lituania",
        "code"      => "LT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 131,
        "name"      => "Luxemburg",
        "code"      => "LU",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 132,
        "name"      => "Macao",
        "code"      => "MO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 133,
        "name"      => "Macedonia",
        "code"      => "MK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 134,
        "name"      => "Madagascar",
        "code"      => "MG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 135,
        "name"      => "Malaezia",
        "code"      => "MY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 136,
        "name"      => "Malawi",
        "code"      => "MW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 137,
        "name"      => "Maldive",
        "code"      => "MV",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 138,
        "name"      => "Mali",
        "code"      => "ML",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 139,
        "name"      => "Malta",
        "code"      => "MT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 140,
        "name"      => "Maroc",
        "code"      => "MA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 141,
        "name"      => "Martinica",
        "code"      => "MQ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 142,
        "name"      => "Mauritania",
        "code"      => "MR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 143,
        "name"      => "Mauritius",
        "code"      => "MU",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 144,
        "name"      => "Mayotte",
        "code"      => "YT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 145,
        "name"      => "Mexic",
        "code"      => "MX",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 146,
        "name"      => "Mianmar",
        "code"      => "MM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 147,
        "name"      => "Monaco",
        "code"      => "MC",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 148,
        "name"      => "Mongolia",
        "code"      => "MN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 149,
        "name"      => "Montserrat",
        "code"      => "MS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 150,
        "name"      => "Mozambic",
        "code"      => "MZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 151,
        "name"      => "Muntenegru",
        "code"      => "ME",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 152,
        "name"      => "Namibia",
        "code"      => "NA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 153,
        "name"      => "Nauru",
        "code"      => "NR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 154,
        "name"      => "Nepal",
        "code"      => "NP",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 155,
        "name"      => "Nicaragua",
        "code"      => "NI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 156,
        "name"      => "Niger",
        "code"      => "NE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 157,
        "name"      => "Nigeria",
        "code"      => "NG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 158,
        "name"      => "Niue",
        "code"      => "NU",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 159,
        "name"      => "Norvegia",
        "code"      => "NO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 160,
        "name"      => "Noua Caledonie",
        "code"      => "NC",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 161,
        "name"      => "Noua Zeelanda",
        "code"      => "NZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 162,
        "name"      => "Olanda",
        "code"      => "NL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 163,
        "name"      => "Oman",
        "code"      => "OM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 164,
        "name"      => "Pakistan",
        "code"      => "PK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 165,
        "name"      => "Palau",
        "code"      => "PW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 166,
        "name"      => "Panama",
        "code"      => "PA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 167,
        "name"      => "Papua Noua Guinee",
        "code"      => "PG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 168,
        "name"      => "Paraguai",
        "code"      => "PY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 169,
        "name"      => "Peru",
        "code"      => "PE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 170,
        "name"      => "Pitcairn",
        "code"      => "PN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 171,
        "name"      => "Polinezia franceza",
        "code"      => "PF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 172,
        "name"      => "Polonia",
        "code"      => "PL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 173,
        "name"      => "Porto Rico",
        "code"      => "PR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 174,
        "name"      => "Portugalia",
        "code"      => "PT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 175,
        "name"      => "Principatul Liechtenstein",
        "code"      => "LI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 176,
        "name"      => "Qatar",
        "code"      => "QA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 177,
        "name"      => "Regatul Lesoto",
        "code"      => "LS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 178,
        "name"      => "Republica Africa Centrala",
        "code"      => "CF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 179,
        "name"      => "Republica Ceha",
        "code"      => "CZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 180,
        "name"      => "Republica Corea",
        "code"      => "KR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 181,
        "name"      => "Republica Democrată Congo",
        "code"      => "CD",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 182,
        "name"      => "Republica Democrata Populara Laos",
        "code"      => "LA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 183,
        "name"      => "Republica Dominicana",
        "code"      => "DO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 184,
        "name"      => "Republica Islamica Iran",
        "code"      => "IR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 185,
        "name"      => "Republica Moldova",
        "code"      => "MD",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 186,
        "name"      => "Republica Seychelles",
        "code"      => "SC",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 187,
        "name"      => "Republica Zimbabwe",
        "code"      => "ZW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 188,
        "name"      => "Réunion",
        "code"      => "RE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 190,
        "name"      => "Ruanda",
        "code"      => "RW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 191,
        "name"      => "Sahara de Vest",
        "code"      => "EH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 192,
        "name"      => "Samoa",
        "code"      => "WS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 193,
        "name"      => "Samoa Americana",
        "code"      => "AS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 194,
        "name"      => "San Marino",
        "code"      => "SM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 195,
        "name"      => "Sao Tome si Principe",
        "code"      => "ST",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 196,
        "name"      => "Senegal",
        "code"      => "SN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 197,
        "name"      => "Serbia/Kosovo",
        "code"      => "RS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 198,
        "name"      => "Sfanta Elena, Inaltarea si Tristan Da Cunha",
        "code"      => "SH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 199,
        "name"      => "Sfanta Lucia",
        "code"      => "LC",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 200,
        "name"      => "Sfantul Bartolomeu",
        "code"      => "BL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 201,
        "name"      => "Sfantul Kitts si Nevis",
        "code"      => "KN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 202,
        "name"      => "Sfantul Maarten (Partea Olandeza)",
        "code"      => "SX",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 203,
        "name"      => "Sfantul Martin (Partea Franceza)",
        "code"      => "MF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 204,
        "name"      => "Sfantul Pierre si Miquelon",
        "code"      => "PM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 205,
        "name"      => "Sfantul Vicentiu si Grenadinele",
        "code"      => "VC",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 206,
        "name"      => "Sierra Leone",
        "code"      => "SL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 207,
        "name"      => "Singapore",
        "code"      => "SG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 250,
        "name"      => "Siria",
        "code"      => "SY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 208,
        "name"      => "Slovacia",
        "code"      => "SK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 209,
        "name"      => "Slovenia",
        "code"      => "SI",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 210,
        "name"      => "Somalia",
        "code"      => "SO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 211,
        "name"      => "Spania",
        "code"      => "ES",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 212,
        "name"      => "Sri Lanka",
        "code"      => "LK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 213,
        "name"      => "Statele Federale ale Micronesiei",
        "code"      => "FM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 214,
        "name"      => "Statele Minore Indepartate ale Statelor Unite",
        "code"      => "UM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 215,
        "name"      => "Statele Unite ale Americii (SUA)",
        "code"      => "US",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 216,
        "name"      => "Sudan",
        "code"      => "SD",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 249,
        "name"      => "Sudanul de Sud",
        "code"      => "SS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 217,
        "name"      => "Suedia",
        "code"      => "SE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 218,
        "name"      => "Suriname",
        "code"      => "SR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 219,
        "name"      => "Svalbard si Jan Mayen",
        "code"      => "SJ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 220,
        "name"      => "Swaziland",
        "code"      => "SZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 221,
        "name"      => "Tadjikistan",
        "code"      => "TJ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 222,
        "name"      => "Tailanda",
        "code"      => "TH",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 223,
        "name"      => "Taiwan, Provincia Chinei",
        "code"      => "TW",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 224,
        "name"      => "Tanzania",
        "code"      => "TZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 225,
        "name"      => "Teritoriile de Sud Franceze",
        "code"      => "TF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 226,
        "name"      => "Teritoriul Britanic din Oceanul Indian",
        "code"      => "IO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 227,
        "name"      => "Teritoriul Palestinian Ocupat",
        "code"      => "PS",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 228,
        "name"      => "Timor-Leste",
        "code"      => "TL",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 229,
        "name"      => "Togo",
        "code"      => "TG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 230,
        "name"      => "Tokelau",
        "code"      => "TK",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 231,
        "name"      => "Tonga",
        "code"      => "TO",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 232,
        "name"      => "Trinidad si Tobago",
        "code"      => "TT",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 233,
        "name"      => "Tunisia",
        "code"      => "TN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 234,
        "name"      => "Turcia",
        "code"      => "TR",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 235,
        "name"      => "Turcmenistan",
        "code"      => "TM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 236,
        "name"      => "Tuvalu",
        "code"      => "TV",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 237,
        "name"      => "Ucraina",
        "code"      => "UA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 238,
        "name"      => "Uganda",
        "code"      => "UG",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 239,
        "name"      => "Ungaria",
        "code"      => "HU",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 240,
        "name"      => "Uruguay",
        "code"      => "UY",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 241,
        "name"      => "Uzbekistan",
        "code"      => "UZ",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 242,
        "name"      => "Vanuatu",
        "code"      => "VU",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 243,
        "name"      => "Vatican (Statul Cetatii Vaticanului)",
        "code"      => "VA",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 244,
        "name"      => "Venezuela",
        "code"      => "VE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 245,
        "name"      => "Vietnam",
        "code"      => "VN",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 246,
        "name"      => "Wallis si Futuna",
        "code"      => "WF",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 247,
        "name"      => "Yemen",
        "code"      => "YE",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 248,
        "name"      => "Zambia",
        "code"      => "ZM",
        "favorite"  => 0,
        "sort"      => null,
        "billing"   => 0,
        "cities"    => 0,
        "locations" => 0,
    ],
    [
        "id"        => 189,
        "name"      => "Romania",
        "code"      => "RO",
        "favorite"  => 0,
        "sort"      => 1,
        "billing"   => 1,
        "cities"    => 13820,
        "locations" => 5009,
    ],
];
